# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Contracts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Contracts.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x43ontracts.proto\" \n\x10\x43\x61rCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\x11\x43\x61rCreateResponse\x12\t\n\x01x\x18\x01 \x01(\t2=\n\nCarService\x12/\n\x06\x43reate\x12\x11.CarCreateRequest\x1a\x12.CarCreateResponseb\x06proto3'
)




_CARCREATEREQUEST = _descriptor.Descriptor(
  name='CarCreateRequest',
  full_name='CarCreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CarCreateRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=51,
)


_CARCREATERESPONSE = _descriptor.Descriptor(
  name='CarCreateResponse',
  full_name='CarCreateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='CarCreateResponse.x', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['CarCreateRequest'] = _CARCREATEREQUEST
DESCRIPTOR.message_types_by_name['CarCreateResponse'] = _CARCREATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CarCreateRequest = _reflection.GeneratedProtocolMessageType('CarCreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _CARCREATEREQUEST,
  '__module__' : 'Contracts_pb2'
  # @@protoc_insertion_point(class_scope:CarCreateRequest)
  })
_sym_db.RegisterMessage(CarCreateRequest)

CarCreateResponse = _reflection.GeneratedProtocolMessageType('CarCreateResponse', (_message.Message,), {
  'DESCRIPTOR' : _CARCREATERESPONSE,
  '__module__' : 'Contracts_pb2'
  # @@protoc_insertion_point(class_scope:CarCreateResponse)
  })
_sym_db.RegisterMessage(CarCreateResponse)



_CARSERVICE = _descriptor.ServiceDescriptor(
  name='CarService',
  full_name='CarService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=85,
  serialized_end=146,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='CarService.Create',
    index=0,
    containing_service=None,
    input_type=_CARCREATEREQUEST,
    output_type=_CARCREATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CARSERVICE)

DESCRIPTOR.services_by_name['CarService'] = _CARSERVICE

# @@protoc_insertion_point(module_scope)
